# Default values for helm-csi-driver-nfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sidecar:
  name: csi-driver-registrar
  image:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v1.3.0
  securityContext: {}

csiDriver:
  name: nfs.csi.k8s.io
  # Build and push to image registry as pulling
  #   docker pull quay.io/k8scsi/csi-driver-nfs:v2.0.0
  # is failing.
  image:
    repository: registry.keyporttech.com:30243/csi-driver-nfs
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v2.0.0
  securityContext:
    privileged: true
    capabilities:
      add: ["SYS_ADMIN"]
    allowPrivilegeEscalation: true
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: csi-driver-nfs-nodeplugin

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

storageClass:
  # If the name is not set, a name is generated using the fullname template.
  name: ""

podAnnotations: {}

podSecurityContext: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
