{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-csi-driver-nfs.fullname" . }}
  labels:
    {{- include "helm-csi-driver-nfs.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-csi-driver-nfs.fullname" . }}
  labels:
    {{- include "helm-csi-driver-nfs.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-csi-driver-nfs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm-csi-driver-nfs.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
